<?php


namespace Magenest\Movie\Block;

use Magenest\Movie\Model\ResourceModel\Actor\ActorCollectionFactory;
use Magento\Backend\Block\Template\Context;
use Magento\Config\Block\System\Config\Form\Field;
use Magento\Framework\Data\Form\Element\AbstractElement;

class rowsOfTableMagenestActor extends Field
{
    protected $_actorCollectionFactory;

    public function __construct(Context $context, array $data = [], ActorCollectionFactory $actorCollectionFactory)
    {
        $this->_actorCollectionFactory = $actorCollectionFactory;
        parent::__construct($context, $data);
    }

    protected function _getElementHtml(AbstractElement $element)
    {
        $count = $this->_actorCollectionFactory->create()->count();
        $element->setValue($count);
        $element->setReadonly(true);
        return parent::_getElementHtml($element); // TODO: Change the autogenerated stub
    }
}
