<div id="test">
    <h1>Day la trang front end</h1>
    <button id="open_modal" data-mage-init='{"hello": {"type": "#open_modal","message": "HELLO WORLD!"}}' type="button">
        Open
        Model
    </button>
    <button id="login_modal" data-mage-init='{"hello": {"type": "#login_modal","message": "Login Modal!"}}'
            type="button">
        Open Magento Login
        Modal
    </button>
    <hr/>
    <div>
        <p>Choose a car</p>
        <!-- <select data-bind="options: cars,
                             optionsCaption: 'Choose....',
                             optionsText: 'name',
                             value: chosenCar"></select>
         <button data-bind="enable: chosenCar,
                            click: resetCar">Clear
         </button>
         <p data-bind="with: chosenCar">
             You have chosen <b data-bind="text: name"></b>
             ($<span data-bind="text: price"></span>)
         </p>-->
       <!-- <select id="sltCars" data-bind="foreach: carsList" options="carsList" optionsText="'name'"
                selectedOptions="chosenCar">
            <option data-bind="text: name"></option>
        </select-->

    </div>
</div>

<!--<script type="text/x-magento-init">
    {
        "#test": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "Magenest_Movie/js/hello"
                    }
                }
            }
        }
    }


</script>
-->
