<?php


namespace Magenest\Movie\Controller\Catalog\Product;



class View extends \Magento\Catalog\Controller\Product\View
{
 public function execute()
 {
     return parent::execute(); // TODO: Change the autogenerated stub
 }
}
